name: bhaktchintamani
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  animated_text_kit: ^4.2.2
  salomon_bottom_bar: ^3.3.1
  flutter_svg: ^1.0.3
  shimmer: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf

    - family: Lato-Bold
      fonts:
        - asset: assets/fonts/Lato-Bold.ttf

    - family: Gujarati
      fonts:
        - asset: assets/fonts/BalooBhai2-Medium.ttf

    - family: Gujarati-Bold
      fonts:
        - asset: assets/fonts/BalooBhai2-Bold.ttf
